### PR TITLE
Add postman collection with current api specs

### LINKED ISSUE #5: Postman Collection
In order to test more easily the API, in the resources folder, add the json of the postman collection that will be generated from importing the swagger documentation into it.

Need #4 to be done and merged

### PR DESCRIPTION
**Pull request by mslowiak**
Closes: #5

### CODE REVIEW

**Comment by ErwanLT** [comment]
@mslowiak thanks, if not too much to ask, can you add tests script in the collection, like testing the return code of the request, and for some the content ?

**Comment by mslowiak** [comment]
> @mslowiak thanks, if not too much to ask, can you add tests script in the collection, like testing the return code of the request, and for some the content ?

I added the validation against 200 http code, but having assertion on body can be really hard to maintain and keep it up to date ;)

**Comment by mslowiak** [comment]
cc: @ErwanLT

**Review by ErwanLT — APPROVED** [review]
to be merged

**Comment by ErwanLT** [comment]
> cc: @ErwanLT

thank for your contribution, it's merged and tag hacktoberfest-accepted

**Pull request merged**
